### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by ryanbmilbourne** [ryanbmilbourne/FantasyRose#1]
# To-dos
- [x] Before moving any further, modify pages to use AJAX for requests.
## Collections
- [x] Create contestants collection in Orchestrate db and populate it
- [x] Support local authentication using remotely stored db.  Salt passwords.
- [x] Create events collection in Orchestrate and means to log events
## Admin tools
- [x] Admin role page shell
- [ ] Contestant manager (add, edit, delete)
- [ ] Events manager (add, edit, delete)
- [ ] User management
## Auction
- [ ] Create auction infrastructure (will flesh this out later)
## Fantasy features
- [x] Route to record  show events
- [ ] Create infrastructure to store weekly data.
- [ ] Contestants route showing their meta data and performance history
- [ ] Email alerts for fantasy events (auction ending, etc)
